[package]
name = "roc_desk_workspace_standalone"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
roc_desk_workspace = { path = "../lib" }
tauri = { version = "2", features = ["wry"] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
